### ISSUE TITLE
generate_csv_from_orders sort/alias issue

### ISSUE THREAD

**Issue by mrmtb** [geman220/ECS-Discord-Bot#11]
in generate_csv_from_orders, the sort function is called at the incorrect step resulting in incorrect output for the alias columns where someone has purchased in multiple orders.

**To Reproduce**
1. run /getorderinfo Away vs LAFC | 2024-02-24
2. identify rows for the following orders [996946, 998192, 998225]; all three rows belong to the same purchaser but are not in sequential order

**Expected behavior**
the first order should have alias information and the other two should be blank

**Additional context**
in the generate_csv_from_orders function, the sort function is called after the row data (and hence the alias logic) is generated. To correct the issue, the sort function should be called on the orders list, instead of the rendered row data.

**Comment by mrmtb** [comment]
I was thinking about this - we could leave the sort where it is, then we'd just need to move the alias logic from where it is to after the sort (go through the sorted list and create the alias content for each row).

**Comment by geman220** [comment]
I'm assuming the PR you submitted resolves this?

**Comment by mrmtb** [comment]
That it does.

**Comment by geman220** [comment]
Cool, I merged and updated the bot.
